"""empty message

Revision ID: 08ba8f4defff
Revises:
Create Date: 2021-01-15 08:34:10.769971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ba8f4defff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('firstname', sa.String(
                        length=40), nullable=False),
                    sa.Column('lastname', sa.String(
                        length=40), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=80), nullable=False),
                    sa.Column('start_time', sa.Date(), nullable=False),
                    sa.Column('end_time', sa.Date(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('background_color', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('memos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('todo_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('todo', sa.String(length=50), nullable=False),
                    sa.Column('priority_level', sa.Integer(), nullable=True),
                    sa.Column('is_done', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('memo_is_display', sa.Boolean(), nullable=False),
                    sa.Column('pomodoro_is_display',
                              sa.Boolean(), nullable=False),
                    sa.Column('day_planner_is_display',
                              sa.Boolean(), nullable=False),
                    sa.Column('todo_is_display', sa.Boolean(), nullable=False),
                    sa.Column('pomodoro_work_interval',
                              sa.Integer(), nullable=False),
                    sa.Column('pomodoro_break_interval',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('todo_items')
    op.drop_table('memos')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
