"""Add user_settings table

Revision ID: 3f9bd12e48a3
Revises: 365525a8c8a3
Create Date: 2021-01-06 16:10:59.703003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9bd12e48a3'
down_revision = '365525a8c8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memo_is_display', sa.Boolean(), nullable=False),
    sa.Column('pomodoro_is_display', sa.Boolean(), nullable=False),
    sa.Column('day_planner_is_display', sa.Boolean(), nullable=False),
    sa.Column('todo_is_display', sa.Boolean(), nullable=False),
    sa.Column('pomodoro_work_interval', sa.Integer(), nullable=False),
    sa.Column('pomodoro_break_interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
